gText_Birch_Welcome::
	.string "Alyssa! Thank goodness you're here! \n"
	.string "I'm your neighbourhood POKéMON \l"
	.string "professor, BIRCH. \p"
	.string "I need your help...They have \n"
	.string "taken BRENDAN! \p"
	.string "The evil team Progressive must \n"
	.string "be stopped!\p"
	.string "I know that you're the \n"
	.string "only one that can do this.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I will be giving you this\n"
	.string "POKéMON, Dedenne.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Dedenne is very powerful, but only\n"
	.string "in the hands of a powerful trainer.\p"
	.string "It is up to you to bring forth\n"
	.string "the power of this little yellow rat.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, I've got a bit of dementia \n"
	.string "and I can't seem to remember. \p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name again?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay! Thanks {PLAYER}{KUN}.\p"
	.string "My brain isn't quite as sharp\n"
	.string "as it used to be.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "When you wake up, Dedenne\n"
	.string "will be next to you in a POKé BALL.\p"
	.string "Take your little yellow rat \n"
	.string "and save BRENDAN! \p"
	.string "$"
